displayName: config
description: |
  A set of config properties for the UI which are driven from the services
type:
    member-readonly:
        member-example: !include "config.example.json"
        member-schema: Config