#%RAML 0.8
title: Get Case Information
version: 1.0
#baseUri: http://localhost:8081
baseUri: http://localhost:8087/hud-esb/edw/api/v1.0
#baseUri: https://esb-t-lnx-api.hud.dev/hud-esb/edw/api/v1.0
mediaType: application/json
documentation:
  - title: Get Case API
    content : Receive Case Information.
#securedBy: [oauth_2_0: { scopes: [ "urn:hud:esb:api:portfolio:get:loan:case" ] } ]
#securitySchemes:
#  - oauth_2_0: !include securitySchemes/oauth_2_0.raml


/case:
  description: Provide Case Number and receive full record.
  get:
    description: Provide Case number and receive its record.
    headers:
    queryParameters:
      caseid:
    responses:
      200:
        body:
          application/json:
            schema: !include caseResponseSchema.json
      400:
        headers:
          application/json:
            type: string
        body:
          application/json:
      500:
        headers:
          application/json:
            type: string
        body:
          application/json:
